### ISSUE TITLE
Any chance you could push a release?

### ISSUE THREAD

**Issue by StuporHero** [Ardesco/driver-binary-downloader-maven-plugin#92]
It's been almost 2 years since 1.0.17, and I could really use firefox support. I can throw some bucks your way, too, since this is for a commercial project.

**Comment by Ardesco** [comment]
Geckodriver (Firefox) support has been in since 2016.  What specific problem are you having around Firefox?

**Comment by Ardesco** [comment]
@StuporHero any update on this?  What is your specific problem?

**Comment by StuporHero** [comment]
@Ardesco There is no Firefox support in 1.0.17. It was added after. See [1.0.17 BinaryType.java](https://github.com/Ardesco/driver-binary-downloader-maven-plugin/blob/1.0.17/src/main/java/com/lazerycode/selenium/repository/BinaryType.java) and [master BinaryType.java](https://github.com/Ardesco/driver-binary-downloader-maven-plugin/blob/master/src/main/java/com/lazerycode/selenium/repository/BinaryType.java).

**Comment by Ardesco** [comment]
I think I understand, you are talking about downloading a copy of Firefox the browser, not firefoxdriver (Marionette, or wires).

**Comment by StuporHero** [comment]
Yes.

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
Going to have to investigate more at the weekend

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
looks like Rultor is failing to decrypt the files at the moment, not sure why to be honest.  I've regenerated the GPG key on this side, I've re-encrypted all the files and tried using different docker containers.  Always failing at the same point which would appear to be a bad passphrase for the Rultor decryption part.

**Comment by Ardesco** [comment]
@rultor release, tag is 1.0.18

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`

**Comment by Ardesco** [comment]
@rultor release, tag=`1.0.18`
