### ISSUE TITLE
Not able to download the latest Chrome Edge Driver Binary

### ISSUE THREAD

**Issue by ravaiyapuri** [Ardesco/driver-binary-downloader-maven-plugin#95]
It looks like the list of BinaryTypes (for possible names) does not include the latest Chromium based Edge. The Driver binary name is msedgedriver.

**Comment by Ardesco** [comment]
Fixed by https://github.com/Ardesco/driver-binary-downloader-maven-plugin/commit/cb0278e93317251c42f37f55e4ae914ef8832924
